FROM ghcr.io/imbev/almalinux-gnome:10-kitten

COPY ../scripts /scripts

RUN /scripts/os-info.sh

RUN /scripts/gnome-shell-extensions.sh

RUN /scripts/gnome-shell-titlebar.sh

RUN /scripts/lint.sh

RUN /scripts/clean.sh
