name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman make

      - name: Login to Quay.io
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | podman login quay.io --username ${{ secrets.QUAY_USERNAME }} --password-stdin

      - name: Build and push
        run: |
          IMAGE_NAME=quay.io/almalinux-atomic-workstation/almalinux-atomic-workstation:latest
          make IMAGE_NAME=${IMAGE_NAME}
          sudo podman push ${IMAGE_NAME}
